// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHPpJGaC1UoHkJTT1ZSOVbnV8FuPSSN4w',
    appId: '1:479718151227:web:2ca865fc6a0d4b80a5f81e',
    messagingSenderId: '479718151227',
    projectId: 'flutter-instagram-clone-8e0ba',
    authDomain: 'flutter-instagram-clone-8e0ba.firebaseapp.com',
    storageBucket: 'flutter-instagram-clone-8e0ba.appspot.com',
    measurementId: 'G-VNBKCV2PSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADAjzLnoYSLYTtnWmkWnUWnxhaJd66dX0',
    appId: '1:479718151227:android:e2a4121eeea23290a5f81e',
    messagingSenderId: '479718151227',
    projectId: 'flutter-instagram-clone-8e0ba',
    storageBucket: 'flutter-instagram-clone-8e0ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtBYH2UzubQMDStXS3tn1tIAvjLyVu3_8',
    appId: '1:479718151227:ios:21db148be029b6bba5f81e',
    messagingSenderId: '479718151227',
    projectId: 'flutter-instagram-clone-8e0ba',
    storageBucket: 'flutter-instagram-clone-8e0ba.appspot.com',
    iosClientId: '479718151227-us249acvikf5iusij3sh9bg64gd3ne8d.apps.googleusercontent.com',
    iosBundleId: 'com.flutter.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtBYH2UzubQMDStXS3tn1tIAvjLyVu3_8',
    appId: '1:479718151227:ios:214a4c47a942ad8ca5f81e',
    messagingSenderId: '479718151227',
    projectId: 'flutter-instagram-clone-8e0ba',
    storageBucket: 'flutter-instagram-clone-8e0ba.appspot.com',
    iosClientId: '479718151227-k5um91dtubueon5lk8lo1hr3db468dn9.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFlutterApp',
  );
}
