// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIDcd5K5FPK3C9bq1V3hDGroyPYXI1TxA',
    appId: '1:734481827442:web:bb491214da3b8e935424eb',
    messagingSenderId: '734481827442',
    projectId: 'zcam-3d94f',
    authDomain: 'zcam-3d94f.firebaseapp.com',
    storageBucket: 'zcam-3d94f.appspot.com',
    measurementId: 'G-5RYRHYGH4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUwXDFsY_yHBezsZr6ziXwNtx6__Hu0kA',
    appId: '1:734481827442:android:a3b5d8c11835bff95424eb',
    messagingSenderId: '734481827442',
    projectId: 'zcam-3d94f',
    storageBucket: 'zcam-3d94f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmznW1oO1KGJbF8S8So5u7Hh1137unBg8',
    appId: '1:734481827442:ios:24d36cbdb8a69afc5424eb',
    messagingSenderId: '734481827442',
    projectId: 'zcam-3d94f',
    storageBucket: 'zcam-3d94f.appspot.com',
    iosBundleId: 'com.icts.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmznW1oO1KGJbF8S8So5u7Hh1137unBg8',
    appId: '1:734481827442:ios:f8bf8ce874e36b045424eb',
    messagingSenderId: '734481827442',
    projectId: 'zcam-3d94f',
    storageBucket: 'zcam-3d94f.appspot.com',
    iosBundleId: 'com.example.myFlutterApp',
  );
}
